### ISSUE TITLE
Table with metadata

### ISSUE THREAD

**Issue by mishka88ru** [contextgarden/not-so-short-introduction-to-context#10]
Hi.

In the book there is a 3rd part about _Particular Issues_. There is a very common national and/or corporation requirement to add document metadata on the page, with a complex layout. I know how to do it manually with MS Word, but how to make it using ConTeXt?

More precisely, how can I put every single page into the table with some information about the document? For example (also there is a similar issue here: https://github.com/Mogztter/asciidoctor-web-pdf/issues/128#issuecomment-556087927, with more details):
 
![изображение](https://user-images.githubusercontent.com/44462629/122094623-09dc4e00-ce15-11eb-84d8-a28dd04c595a.png)

**Comment by adityam** [comment]
This is not a forum on help regarding context. Better to ask such questions on the [context mailing list](https://wiki.contextgarden.net/Mailing_Lists)
