### ISSUE TITLE
bookmarks redundant bakcslash and bracket

### ISSUE THREAD

**Issue by Passw** [contextgarden/not-so-short-introduction-to-context#2]
Open `introCTX_eng.pdf` with `Adobe Acrobat Reader DC` under Win10.
There are several redundant `\` and `{`, `}`

**Comment by garulfogb** [comment]
yep, ConTeXt proposes command to automatically improve bookmark handling. I have to check that.

**Comment by garulfogb** [comment]
Could you please check with the current version.
Under Okular Linux, redundant \ and {, } are gone
