### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by lrusso96** [contextgarden/not-so-short-introduction-to-context#20]
When I try to compile the English version I obtain the following:
```
tex error  > tex error on line 1332 in file 01_BodyMatter/b08_Lists.mkiv: The file ended when scanning an argument.
mtx-context   | fatal error: return code: 1
```

**Comment by lrusso96** [comment]
Any help about this? @garulfogb @AlanoDel

**Comment by AlanoDel** [comment]
What do you mean by "help"

garulfogb is the main translator to French
AlanoDel is a contributor to the translation

Le mar. 31 août 2021 à 08:58, Luigi Russo ***@***.***> a
écrit :

**Comment by lrusso96** [comment]
> What do you mean by "help" garulfogb is the main translator to French AlanoDel is a contributor to the translation Le mar. 31 août 2021 à 08:58, Luigi Russo 

Since you are among the most active contributors, I've pinged you. Have you experienced any sort of compilation error for the English version?

**Comment by garulfogb** [comment]
1/ I get no error with  context -version = 2020.03.10 14:44 (Linux Debian default)

2/ I get  the "01_BodyMatter/b08_Lists.mkiv: The file ended when scanning an argument" error with 
- context -version = 2021.08.24 22:16
- context -version = 2021.08.30 19:56

I am investigating and come back to you

**Comment by garulfogb** [comment]
Ok, should be OK now. @lrusso96 Could you please confirm ?

I replaced the  \head commands by \starthead \stophead which seems to be required now by LMTX

**Comment by AlanoDel** [comment]
I didn't compile the English version.
I am only checking the French version

Le mar. 31 août 2021 à 14:12, Luigi Russo ***@***.***> a
écrit :

**Comment by garulfogb** [comment]
Corrections added to spanish version.
Sorry for such a late answer (26 days...)
I hope you will stay interested to improve the document.

**Comment by lrusso96** [comment]
> 
> 
> Ok, should be OK now. @lrusso96 Could you please confirm ?
> 
> I replaced the \head commands by \starthead \stophead which seems to be required now by LMTX

Seems fixed now, thanks a lot.
