### ISSUE TITLE
Commit 3f4866c broke Serbian book

### ISSUE THREAD

**Issue by eevan78** [contextgarden/not-so-short-introduction-to-context#29]
Commit [3f4866c](https://github.com/contextgarden/not-so-short-introduction-to-context/commit/3f4866c3ecba13623241560f7562870a38edc293) completely broke the book.
Also, \somewhere was working perfectly fine, as I have added the following in the environment:
`\setupreferencing[doublesided=no] % Подешавање за \somewhere пример`

![image](https://user-images.githubusercontent.com/27575106/159920732-881d55d9-982a-4362-a297-be732801ce1b.png)

I have used Garamond Premier Pro because it has a proper support for all Serbian glyphs, especialy localized italics.
And compiled it with LMTX.

**Comment by garulfogb** [comment]
Hi eevant78, I re-integrated the content of  your fork, as well as the required fonts (and the script for auto-build use of it)
https://github.com/contextgarden/not-so-short-introduction-to-context/blob/main/.github/workflows/main.yml

**Comment by garulfogb** [comment]
see above
