### ISSUE TITLE
How should I start translating this book to Chinese?

### ISSUE THREAD

**Issue by Fusyong** [contextgarden/not-so-short-introduction-to-context#31]
Thanks for this great book.

I would like to translate this book from the English version into simplified Chinese.  How should I start now? Should I translate all the documents and then submit them? Or fork this repository , add a folder named zh-CHS for the Simplified Chinese version, and submit the results to this folder as I progress?

**Comment by adityam** [comment]
You can fork the repo, make appropriate changes in a separate folder and submit the changes as a pull request to this repo.

**Comment by Fusyong** [comment]
I get it. Thank you.

**Comment by johnzhou721** [comment]
@Fusyong Still workin' on this?
